### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by xiaowu55** [WuIFan/Spotify_MergePlayList#1]
Traceback (most recent call last):
  File "main.py", line 80, in <module>
    mp.merge()
  File "main.py", line 49, in merge
    tracks = self.getTracks(playlist1_id)
UnboundLocalError: local variable 'playlist1_id' referenced before assignment

**Comment by iamivanwu** [comment]
Thanks for your feedback.
The error occurred because the playlist is not set to public. Please try to make the playlist public and try again.
Please reply me if there is any progress.

**Comment by xiaowu55** [comment]
Has been set to public but the problem still exists
xiaowu:Spotify_MergePlayList-master mac$ python main.py 36kEIKUTS0QPHjgDDCwjeV 231b5xyK5nDaDxYgJFsJze 27ZBmclHlklmEUx9YfVNNv
Traceback (most recent call last):
  File "main.py", line 80, in <module>
    mp.merge()
  File "main.py", line 49, in merge
    tracks = self.getTracks(playlist1_id)
UnboundLocalError: local variable 'playlist1_id' referenced before assignment

**Comment by iamivanwu** [comment]
The parameter to run this program must be the playlist name.
Like this:
python main.py target_name playlist1_name playlist2_name

**Comment by xiaowu55** [comment]
How can I find my playlist name?

**Comment by iamivanwu** [comment]
![圖片 2](https://user-images.githubusercontent.com/9366429/82659187-d9020780-9c5a-11ea-9da9-cc515ba13653.png)
Open your Spotify app, on the left, there should be a category for playlists. Below is the name of the playlist.
Note: You can only run this code in playlists you create

**Comment by xiaowu55** [comment]
xiaowu:Spotify_MergePlayList-master mac$ python main.py ci a b
('track number : ', 172)
('track number : ', 160)
('Total tracks : ', 225)
Traceback (most recent call last):
  File "main.py", line 80, in <module>
    mp.merge()
  File "main.py", line 58, in merge
    self.addTracks(sorted_track)
  File "main.py", line 38, in addTracks
    toAdd.clear()
AttributeError: 'list' object has no attribute 'clear'

**Comment by iamivanwu** [comment]
The python version of macOS defaults to 2.7, but I write this code with python 3.5.
If you want to run this program without change your python version, you can modify the source code in main.py, and change the line 38's `toAdd.clear()` to `del toAdd[:]`

**Comment by xiaowu55** [comment]
OK

**Comment by xiaowu55** [comment]
Thank you very much

**Comment by iamivanwu** [comment]
:blush:
